name: virtual_card
description: Criação e compartilhamento de imagens personalizadas
version: 2.1.8+50

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  cupertino_icons: ^1.0.2
#  esys_flutter_share: ^1.0.2
  share: ^2.0.1
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  shared_preferences: ^2.0.5
  flutter_cache_manager: ^3.0.1
#  flutter_statusbarcolor: ^0.2.3
  lottie: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  keyboard_actions: ^3.4.0
  carousel_slider: ^4.0.0-nullsafety.0
#  connectivity: ^2.0.1
  rxdart: ^0.26.0
  google_fonts: ^2.0.0
  json_serializable: ^4.1.1
  path_provider: ^2.0.1
  unicons: ^2.0.1
#  ripple_color_selection: ^0.0.4
  google_mobile_ads: ^0.12.1+1
  provider: ^5.0.0
  permission_handler: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#F2F2F2"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/transparent.png
    - assets/lottiefiles/done.json
    - assets/lottiefiles/fill_cell.json
    - assets/lottiefiles/fill_name.json
    - assets/lottiefiles/pencil_write.json
    - assets/lottiefiles/services.json
    - assets/lottiefiles/trophy.json
    - assets/lottiefiles/wave_loading.json
    - assets/lottiefiles/swipe-left-to-right.json
    - assets/lottiefiles/position.json
    - assets/lottiefiles/five-stars.json
    - assets/lottiefiles/share.json
    - assets/lottiefiles/background.json
    - assets/images/back_1.jpg
    - assets/images/back_2.jpg
    - assets/images/back_3.jpg
    - assets/images/back_4.jpg
    - assets/images/back_5.jpg
    - assets/images/back_6.jpg
    - assets/images/back_7.jpg
    - assets/images/back_8.jpg
    - assets/images/back_9.jpg
    - assets/images/back_10.jpg
    - assets/images/back_11.jpg
    - assets/images/back_12.jpg
    - assets/images/back_13.jpg
    - assets/images/back_14.jpg
    - assets/images/back_15.jpg
    - assets/images/back_16.jpg
    - assets/images/back_17.jpg
    - assets/images/back_18.jpg
    - assets/images/back_19.jpg
    - assets/images/back_20.jpg
    - assets/images/back_21.gif
    - assets/images/back_22.gif
    - assets/images/back_23.gif
    - assets/images/back_24.gif
    - assets/images/back_25.gif
    - assets/images/back_26.gif
    - assets/images/back_27.gif
    - assets/images/back_28.gif
    - assets/images/back_29.gif
    - assets/images/back_30.gif
    - assets/images/back_31.gif
    - assets/images/back_32.gif
    - assets/images/back_33.gif
    - assets/images/back_34.gif
    - assets/images/back_35.gif
    - assets/images/back_36.gif
    - assets/images/back_37.gif
    - assets/images/back_38.gif
    - assets/images/back_39.gif
    - assets/images/back_40.gif
    - assets/images/back_41.gif
    - assets/images/back_42.gif
    - assets/images/back_43.gif
    - assets/images/back_44.gif
    - assets/images/back_45.gif
    - assets/images/back_46.gif
    - assets/images/back_47.gif
    - assets/images/back_48.gif
    - assets/images/back_49.gif
    - assets/images/back_50.gif
    - assets/images/back_51.gif
    - assets/images/back_52.gif
    - assets/images/back_53.gif
    - assets/images/back_54.gif
    - assets/images/back_55.gif
    - assets/images/back_56.gif
    - assets/images/back_57.gif
    - assets/images/back_58.gif
    - assets/images/back_59.gif
    - assets/images/back_60.gif

flutter_intl:
  main_locale: en_US
  enabled: true
