name: virtual_card
description: Criação e envio de cartão de visita digital
version: 1.1.4+26

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^8.10.0
  mask_text_input_formatter: ^1.1.0
  cupertino_icons: ^1.0.0
#  esys_flutter_share: ^1.0.2
  share: ^0.6.5+3
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  shared_preferences: ^0.5.12+2
#  flutter_statusbarcolor: ^0.2.3
  lottie: ^0.6.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  keyboard_actions: ^3.3.1+1
  carousel_slider: ^2.3.1
  connectivity: ^0.4.9+5
  rxdart: ^0.24.1
  bloc_pattern: ^2.5.1
  json_serializable: ^3.5.0
  path_provider: ^1.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#F2F2F2"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/transparent.png
    - assets/lottiefiles/done.json
    - assets/lottiefiles/fill_cell.json
    - assets/lottiefiles/fill_name.json
    - assets/lottiefiles/pencil_write.json
    - assets/lottiefiles/services.json
    - assets/lottiefiles/trophy.json
    - assets/lottiefiles/wave_loading.json
    - assets/lottiefiles/swipe-left-to-right.json
    - assets/lottiefiles/position.json
    - assets/lottiefiles/five-stars.json
    - assets/lottiefiles/share.json
    - assets/lottiefiles/background.json