name: virtual_card
description: Criação e envio de cartão de visita digital
version: 1.2.2+30

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^8.10.0
  mask_text_input_formatter: ^1.1.0
  cupertino_icons: ^1.0.0
#  esys_flutter_share: ^1.0.2
  share: ^0.6.5+3
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  shared_preferences: ^0.5.12+2
#  flutter_statusbarcolor: ^0.2.3
  lottie: ^0.6.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  keyboard_actions: ^3.3.1+1
  carousel_slider: ^2.3.1
  connectivity: ^2.0.0
  rxdart: ^0.24.1
  bloc_pattern: ^2.5.1
  json_serializable: ^3.5.0
  path_provider: ^1.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#F2F2F2"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/transparent.png
    - assets/lottiefiles/done.json
    - assets/lottiefiles/fill_cell.json
    - assets/lottiefiles/fill_name.json
    - assets/lottiefiles/pencil_write.json
    - assets/lottiefiles/services.json
    - assets/lottiefiles/trophy.json
    - assets/lottiefiles/wave_loading.json
    - assets/lottiefiles/swipe-left-to-right.json
    - assets/lottiefiles/position.json
    - assets/lottiefiles/five-stars.json
    - assets/lottiefiles/share.json
    - assets/lottiefiles/background.json
  fonts:
    - family: Arcade
      fonts:
        - asset: assets/fonts/Arcade.ttf
    - family: Champagne
      fonts:
        - asset: assets/fonts/Champagne.ttf
    - family: Dancing
      fonts:
        - asset: assets/fonts/Dancing.ttf
    - family: Dreams
      fonts:
        - asset: assets/fonts/Dreams.ttf
    - family: Excentric
      fonts:
        - asset: assets/fonts/Excentric.ttf
    - family: Forgot
      fonts:
        - asset: assets/fonts/Forgot.ttf
    - family: Giorgino
      fonts:
        - asset: assets/fonts/Giorgino.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Opficio
      fonts:
        - asset: assets/fonts/Opficio.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/Playfair.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf
    - family: Walkway
      fonts:
        - asset: assets/fonts/Walkway.ttf
    - family: Advark
      fonts:
        - asset: assets/fonts/Advark.ttf
    - family: Aquarium
      fonts:
        - asset: assets/fonts/Aquarium.ttf
    - family: Athletic
      fonts:
        - asset: assets/fonts/Athletic.ttf
    - family: Barcode
      fonts:
        - asset: assets/fonts/Barcode.ttf
    - family: Bendit
      fonts:
        - asset: assets/fonts/Bendit.ttf
    - family: Bernardo
      fonts:
        - asset: assets/fonts/Bernardo.ttf
    - family: Blacklisted
      fonts:
        - asset: assets/fonts/Blacklisted.ttf
    - family: Blocks
      fonts:
        - asset: assets/fonts/Blocks.ttf
    - family: Blomster
      fonts:
        - asset: assets/fonts/Blomster.ttf
    - family: Caricature
      fonts:
        - asset: assets/fonts/Caricature.ttf
    - family: Cartoon
      fonts:
        - asset: assets/fonts/Cartoon.ttf
    - family: Castiron
      fonts:
        - asset: assets/fonts/Castiron.ttf
    - family: Catpaw
      fonts:
        - asset: assets/fonts/Catpaw.ttf
    - family: Circus
      fonts:
        - asset: assets/fonts/Circus.ttf
    - family: Cowboys
      fonts:
        - asset: assets/fonts/Cowboys.ttf
    - family: Flowers
      fonts:
        - asset: assets/fonts/Flowers.ttf
    - family: Fuzzy
      fonts:
        - asset: assets/fonts/Fuzzy.ttf
    - family: Grobol
      fonts:
        - asset: assets/fonts/Grobol.ttf
    - family: Hannah
      fonts:
        - asset: assets/fonts/Hannah.ttf
    - family: Heineken
      fonts:
        - asset: assets/fonts/Heineken.ttf
    - family: Hischool
      fonts:
        - asset: assets/fonts/Hischool.ttf
    - family: Icecold
      fonts:
        - asset: assets/fonts/Icecold.ttf
    - family: Icecream
      fonts:
        - asset: assets/fonts/Icecream.ttf
    - family: LokiCola
      fonts:
        - asset: assets/fonts/LokiCola.ttf
    - family: Melody
      fonts:
        - asset: assets/fonts/Melody.ttf
    - family: Milestone
      fonts:
        - asset: assets/fonts/Milestone.otf
    - family: Minnie
      fonts:
        - asset: assets/fonts/Minnie.ttf
    - family: Music
      fonts:
        - asset: assets/fonts/Music.ttf
    - family: Playtoy
      fonts:
        - asset: assets/fonts/Playtoy.ttf
    - family: Porkys
      fonts:
        - asset: assets/fonts/Porkys.ttf
    - family: Potter
      fonts:
        - asset: assets/fonts/Potter.ttf
    - family: Resort
      fonts:
        - asset: assets/fonts/Resort.ttf
    - family: Armywar
      fonts:
        - asset: assets/fonts/Armywar.otf
    - family: School
      fonts:
        - asset: assets/fonts/School.ttf
    - family: Smoke
      fonts:
        - asset: assets/fonts/Smoke.ttf
    - family: Vanessa
      fonts:
        - asset: assets/fonts/Vanessa.ttf
    - family: Vintage
      fonts:
        - asset: assets/fonts/Vintage.ttf
    - family: Zornic
      fonts:
        - asset: assets/fonts/Zornic.ttf

