class CardInfo {
  String name = '';
  String occupation = '';
  String phone = '';
  String photo = '';
  String email = '';
  String facebook = '';
  String instagram = '';
  String twitter = '';
  String linkedin = '';
  String youtube = '';
  String website = '';
  String colorTextAbove = '0.0';
  String colorTextBelow = '0.0';
  String nameIcon = '';
  String occupationIcon = '';
  String phoneIcon = '';
  String photoIcon = '';
  String emailIcon = '';
  String facebookIcon = '';
  String instagramIcon = '';
  String twitterIcon = '';
  String linkedinIcon = '';
  String youtubeIcon = '';
  String websiteIcon = '';
  bool hasName = true;
  bool hasOccupation = true;
  bool hasPhone = true;
  bool hasPhoto = true;
  bool photoCircle = true;
  bool hasEmail = false;
  bool hasFacebook = false;
  bool hasInstagram = false;
  bool hasTwitter = false;
  bool hasLinkedin = false;
  bool hasYoutube = false;
  bool hasWebsite = false;
  double posXName = 10;
  double posXOccupation = 10;
  double posXPhone = 10;
  double posXPhoto = 10;
  double posXEmail = 10;
  double posXFacebook = 10;
  double posXLinkedin = 10;
  double posXInstagram = 10;
  double posXTwitter = 10;
  double posXYoutube = 10;
  double posXWebsite = 10;
  double posYName = 20;
  double posYOccupation = 50;
  double posYPhone = 80;
  double posYPhoto = 150;
  double posYEmail = 380;
  double posYFacebook = 410;
  double posYLinkedin = 440;
  double posYInstagram = 470;
  double posYTwitter = 500;
  double posYYoutube = 530;
  double posYWebsite = 560;
  double scaleName = 1.0;
  double scaleOccupation = 1.0;
  double scalePhone = 1.0;
  double scalePhoto = 1.0;
  double scaleEmail = 1.0;
  double scaleFacebook = 1.0;
  double scaleLinkedin = 1.0;
  double scaleInstagram = 1.0;
  double scaleTwitter = 1.0;
  double scaleYoutube = 1.0;
  double scaleWebsite = 1.0;
  String colorName = '';
  String colorOccupation = '';
  String colorPhone = '';
  String colorPhoto = '';
  String colorEmail = '';
  String colorFacebook = '';
  String colorLinkedin = '';
  String colorInstagram = '';
  String colorTwitter = '';
  String colorYoutube = '';
  String colorWebsite = '';
  String fontName = 'Montserrat';
  String fontOccupation = 'Montserrat';
  String fontPhone = 'Montserrat';
  String fontPhoto = 'Montserrat';
  String fontEmail = 'Montserrat';
  String fontFacebook = 'Montserrat';
  String fontLinkedin = 'Montserrat';
  String fontInstagram = 'Montserrat';
  String fontTwitter = 'Montserrat';
  String fontYoutube = 'Montserrat';
  String fontWebsite = 'Montserrat';
  String version = '0';
  String opacity = '1.0';
  double angleName = 0.0;
  double angleOccupation = 0.0;
  double anglePhone = 0.0;
  double anglePhoto = 0.0;
  double angleEmail = 0.0;
  double angleFacebook = 0.0;
  double angleLinkedin = 0.0;
  double angleInstagram = 0.0;
  double angleTwitter = 0.0;
  double angleYoutube = 0.0;
  double angleWebsite = 0.0;
  
  CardInfo({
    this.name = '', 
    this.occupation = '', 
    this.phone = '', 
    this.photo = '', 
    this.email = '', 
    this.facebook = '',
    this.instagram = '', 
    this.twitter = '', 
    this.linkedin = '', 
    this.youtube = '', 
    this.website = '',
    this.colorTextAbove = '', 
    this.colorTextBelow = '', 
    this.nameIcon = '', 
    this.occupationIcon = '', 
    this.phoneIcon = '',
    this.photoIcon = '', 
    this.emailIcon = '', 
    this.facebookIcon = '', 
    this.instagramIcon = '', 
    this.twitterIcon = '',
    this.linkedinIcon = '', 
    this.youtubeIcon = '',
    this.websiteIcon = '', 
    this.hasName = true, 
    this.hasOccupation = true,
    this.hasPhone = true, 
    this.hasPhoto = true, 
    this.photoCircle = true, 
    this.hasEmail = false, 
    this.hasFacebook = false, 
    this.hasInstagram = false,
    this.hasTwitter = false, 
    this.hasLinkedin = false, 
    this.hasYoutube = false, 
    this.hasWebsite = false, 
    this.posXName = 10,
    this.posXOccupation = 10, 
    this.posXPhone = 10, 
    this.posXPhoto = 10, 
    this.posXEmail = 10, 
    this.posXFacebook = 10,
    this.posXInstagram = 10, 
    this.posXTwitter = 10, 
    this.posXLinkedin = 10, 
    this.posXYoutube = 10,
    this.posXWebsite = 10, 
    this.posYName = 20, 
    this.posYOccupation = 50, 
    this.posYPhone = 80, 
    this.posYPhoto = 150,
    this.posYEmail = 380, 
    this.posYFacebook = 410, 
    this.posYLinkedin = 440, 
    this.posYInstagram = 470, 
    this.posYTwitter = 500,
    this.posYYoutube = 530, 
    this.posYWebsite = 560, 
    this.scaleName = 1.0, 
    this.scaleOccupation = 1.0, 
    this.scalePhone = 1.0, 
    this.scalePhoto = 1.0,
    this.scaleEmail = 1.0, 
    this.scaleFacebook = 1.0, 
    this.scaleInstagram = 1.0, 
    this.scaleTwitter = 1.0, 
    this.scaleLinkedin = 1.0,
    this.scaleYoutube = 1.0, 
    this.scaleWebsite = 1.0, 
    this.colorName = '', 
    this.colorOccupation = '', 
    this.colorPhone = '', 
    this.colorPhoto = '', 
    this.colorEmail = '', 
    this.colorFacebook = '', 
    this.colorLinkedin = '', 
    this.colorInstagram = '', 
    this.colorTwitter = '', 
    this.colorYoutube = '', 
    this.colorWebsite = '', 
    this.fontName = 'Montserrat', 
    this.fontOccupation = 'Montserrat', 
    this.fontPhone = 'Montserrat', 
    this.fontPhoto = 'Montserrat', 
    this.fontEmail = 'Montserrat', 
    this.fontFacebook = 'Montserrat', 
    this.fontLinkedin = 'Montserrat', 
    this.fontInstagram = 'Montserrat', 
    this.fontTwitter = 'Montserrat', 
    this.fontYoutube = 'Montserrat', 
    this.fontWebsite = 'Montserrat', 
    this.version = '0', 
    this.opacity = '1.0',
    this.angleName = 0.0, 
    this.angleOccupation = 0.0, 
    this.anglePhone = 0.0, 
    this.anglePhoto = 0.0, 
    this.angleEmail = 0.0, 
    this.angleFacebook = 0.0,
    this.angleLinkedin = 0.0, 
    this.angleInstagram = 0.0, 
    this.angleTwitter = 0.0, 
    this.angleYoutube = 0.0, 
    this.angleWebsite = 0.0});
  
  CardInfo.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    occupation = json['occupation'];
    phone = json['phone'];
    photo = json['photo'];
    email = json['email'];
    facebook = json['facebook'];
    instagram = json['instagram'];
    twitter = json['twitter'];
    linkedin = json['linkedin'];
    youtube = json['youtube'];
    website = json['website'];
    colorTextAbove = json['colorTextAbove'];
    colorTextBelow = json['colorTextBelow'];
    nameIcon = json['nameIcon'];
    occupationIcon = json['occupationIcon'];
    phoneIcon = json['phoneIcon'];
    photoIcon = json['photoIcon'];
    emailIcon = json['emailIcon'];
    facebookIcon = json['facebookIcon'];
    instagramIcon = json['instagramIcon'];
    twitterIcon = json['twitterIcon'];
    linkedinIcon = json['linkedinIcon'];
    youtubeIcon = json['youtubeIcon'];
    websiteIcon = json['websiteIcon'];
    hasName = json['hasName'];
    hasOccupation = json['hasOccupation'];
    hasPhone = json['hasPhone'];
    hasPhoto = json['hasPhoto'];
    photoCircle = json['photoCircle'];
    hasEmail = json['hasEmail'];
    hasFacebook = json['hasFacebook'];
    hasInstagram = json['hasInstagram'];
    hasTwitter = json['hasTwitter'];
    hasLinkedin = json['hasLinkedin'];
    hasYoutube = json['hasYoutube'];
    hasWebsite = json['hasWebsite'];
    posXName = json['posXName'];
    posXOccupation = json['posXOccupation'];
    posXPhone = json['posXPhone'];
    posXPhoto = json['posXPhoto'];
    posXEmail = json['posXEmail'];
    posXFacebook = json['posXFacebook'];
    posXInstagram = json['posXInstagram'];
    posXTwitter = json['posXTwitter'];
    posXLinkedin = json['posXLinkedin'];
    posXYoutube = json['posXYoutube'];
    posXWebsite = json['posXWebsite'];
    posYName = json['posYName'];
    posYOccupation = json['posYOccupation'];
    posYPhone = json['posYPhone'];
    posYPhoto = json['posYPhoto'];
    posYEmail = json['posYEmail'];
    posYFacebook = json['posYFacebook'];
    posYInstagram = json['posYInstagram'];
    posYTwitter = json['posYTwitter'];
    posYLinkedin = json['posYLinkedin'];
    posYYoutube = json['posYYoutube'];
    posYWebsite = json['posYWebsite'];
    scaleName = json['scaleName'];
    scaleOccupation = json['scaleOccupation'];
    scalePhone = json['scalePhone'];
    scalePhoto = json['scalePhoto'];
    scaleEmail = json['scaleEmail'];
    scaleFacebook = json['scaleFacebook'];
    scaleInstagram = json['scaleInstagram'];
    scaleTwitter = json['scaleTwitter'];
    scaleLinkedin = json['scaleLinkedin'];
    scaleYoutube = json['scaleYoutube'];
    scaleWebsite = json['scaleWebsite'];
    colorName = json['colorName'];
    colorOccupation = json['colorOccupation'];
    colorPhone = json['colorPhone'];
    colorPhoto = json['colorPhoto'];
    colorEmail = json['colorEmail'];
    colorFacebook = json['colorFacebook'];
    colorInstagram = json['colorInstagram'];
    colorTwitter = json['colorTwitter'];
    colorLinkedin = json['colorLinkedin'];
    colorYoutube = json['colorYoutube'];
    colorWebsite = json['colorWebsite'];
    fontName = json['fontName'];
    fontOccupation = json['fontOccupation'];
    fontPhone = json['fontPhone'];
    fontPhoto = json['fontPhoto'];
    fontEmail = json['fontEmail'];
    fontFacebook = json['fontFacebook'];
    fontInstagram = json['fontInstagram'];
    fontTwitter = json['fontTwitter'];
    fontLinkedin = json['fontLinkedin'];
    fontYoutube = json['fontYoutube'];
    fontWebsite = json['fontWebsite'];
    version = json['version'];
    opacity = json['opacity'];
    angleName = json['angleName'];
    angleOccupation = json['angleOccupation'];
    anglePhone = json['anglePhone'];
    anglePhoto = json['anglePhoto'];
    angleEmail = json['angleEmail'];
    angleFacebook = json['angleFacebook'];
    angleInstagram = json['angleInstagram'];
    angleTwitter = json['angleTwitter'];
    angleLinkedin = json['angleLinkedin'];
    angleYoutube = json['angleYoutube'];
    angleWebsite = json['angleWebsite'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['occupation'] = this.occupation;
    data['phone'] = this.phone;
    data['photo'] = this.photo;
    data['email'] = this.email;
    data['facebook'] = this.facebook;
    data['instagram'] = this.instagram;
    data['twitter'] = this.twitter;
    data['linkedin'] = this.linkedin;
    data['youtube'] = this.youtube;
    data['website'] = this.website;
    data['colorTextAbove'] = this.colorTextAbove;
    data['colorTextBelow'] = this.colorTextBelow;
    data['nameIcon'] = this.nameIcon;
    data['occupationIcon'] = this.occupationIcon;
    data['phoneIcon'] = this.phoneIcon;
    data['photoIcon'] = this.photoIcon;
    data['emailIcon'] = this.emailIcon;
    data['facebookIcon'] = this.facebookIcon;
    data['instagramIcon'] = this.instagramIcon;
    data['twitterIcon'] = this.twitterIcon;
    data['linkedinIcon'] = this.linkedinIcon;
    data['youtubeIcon'] = this.youtubeIcon;
    data['websiteIcon'] = this.websiteIcon;
    data['hasName'] = this.hasName;
    data['hasOccupation'] = this.hasOccupation;
    data['hasPhone'] = this.hasPhone;
    data['hasPhoto'] = this.hasPhoto;
    data['photoCircle'] = this.photoCircle;
    data['hasEmail'] = this.hasEmail;
    data['hasFacebook'] = this.hasFacebook;
    data['hasInstagram'] = this.hasInstagram;
    data['hasTwitter'] = this.hasTwitter;
    data['hasLinkedin'] = this.hasLinkedin;
    data['hasYoutube'] = this.hasYoutube;
    data['hasWebsite'] = this.hasWebsite;
    data['posXName'] = this.posXName;
    data['posXOccupation'] = this.posXOccupation;
    data['posXPhone'] = this.posXPhone;
    data['posXPhoto'] = this.posXPhoto;
    data['posXEmail'] = this.posXEmail;
    data['posXFacebook'] = this.posXFacebook;
    data['posXInstagram'] = this.posXInstagram;
    data['posXTwitter'] = this.posXTwitter;
    data['posXLinkedin'] = this.posXLinkedin;
    data['posXYoutube'] = this.posXYoutube;
    data['posXWebsite'] = this.posXWebsite;
    data['posYName'] = this.posYName;
    data['posYOccupation'] = this.posYOccupation;
    data['posYPhone'] = this.posYPhone;
    data['posYPhoto'] = this.posYPhoto;
    data['posYEmail'] = this.posYEmail;
    data['posYFacebook'] = this.posYFacebook;
    data['posYInstagram'] = this.posYInstagram;
    data['posYTwitter'] = this.posYTwitter;
    data['posYLinkedin'] = this.posYLinkedin;
    data['posYYoutube'] = this.posYYoutube;
    data['posYWebsite'] = this.posYWebsite;
    data['scaleName'] = this.scaleName;
    data['scaleOccupation'] = this.scaleOccupation;
    data['scalePhone'] = this.scalePhone;
    data['scalePhoto'] = this.scalePhoto;
    data['scaleEmail'] = this.scaleEmail;
    data['scaleFacebook'] = this.scaleFacebook;
    data['scaleInstagram'] = this.scaleInstagram;
    data['scaleTwitter'] = this.scaleTwitter;
    data['scaleLinkedin'] = this.scaleLinkedin;
    data['scaleYoutube'] = this.scaleYoutube;
    data['scaleWebsite'] = this.scaleWebsite;
    data['colorName'] = this.colorName;
    data['colorOccupation'] = this.colorOccupation;
    data['colorPhone'] = this.colorPhone;
    data['colorPhoto'] = this.colorPhoto;
    data['colorEmail'] = this.colorEmail;
    data['colorFacebook'] = this.colorFacebook;
    data['colorInstagram'] = this.colorInstagram;
    data['colorTwitter'] = this.colorTwitter;
    data['colorLinkedin'] = this.colorLinkedin;
    data['colorYoutube'] = this.colorYoutube;
    data['colorWebsite'] = this.colorWebsite;
    data['fontName'] = this.fontName;
    data['fontOccupation'] = this.fontOccupation;
    data['fontPhone'] = this.fontPhone;
    data['fontPhoto'] = this.fontPhoto;
    data['fontEmail'] = this.fontEmail;
    data['fontFacebook'] = this.fontFacebook;
    data['fontInstagram'] = this.fontInstagram;
    data['fontTwitter'] = this.fontTwitter;
    data['fontLinkedin'] = this.fontLinkedin;
    data['fontYoutube'] = this.fontYoutube;
    data['fontWebsite'] = this.fontWebsite;
    data['version'] = this.version;
    data['opacity'] = this.opacity;
    data['angleName'] = this.angleName;
    data['angleOccupation'] = this.angleOccupation;
    data['anglePhone'] = this.anglePhone;
    data['anglePhoto'] = this.anglePhoto;
    data['angleEmail'] = this.angleEmail;
    data['angleFacebook'] = this.angleFacebook;
    data['angleInstagram'] = this.angleInstagram;
    data['angleTwitter'] = this.angleTwitter;
    data['angleLinkedin'] = this.angleLinkedin;
    data['angleYoutube'] = this.angleYoutube;
    data['angleWebsite'] = this.angleWebsite;
    return data;
  }
}
